### PR TITLE
Added notifyOnComplete parameter for KernelExecutor

### PR DESCRIPTION
**Pull request by sok82**
Added notifyOnComplete parameter for code execution enabling to send model notifications only when all code execution completed and execution phase is defined 

Possible solve for https://github.com/datalayer/jupyter-ui/issues/290

### CODE REVIEW

**Comment by echarles** [comment]
@sok82 Change look good overall.

Build on CI complains with ` src/components/output/OutputAdapter.ts(85,76): error TS2345: Argument of type 'boolean | undefined' is not assignable to parameter of type 'JSONObject | undefined'.
    Type 'boolean' is not assignable to type 'JSONObject'.`  Is this related to changes introduced in this PR?

**Comment by echarles** [comment]
@sok82 another PR builds fine, so I think the failure is coming from these changes. I would prefer if possible to have it fixed before merging.

**Comment by sok82** [comment]
Hey @echarles,
sorry for waiting - was on the mountain trip without network coverage for long time(

I committed a fix for the error in this commit - https://github.com/datalayer/jupyter-ui/pull/291/commits/5fb502798b4f55d2c96e7ed416e6bcfe5dd620c0

Some new parameter `metadata` of type `JSONObject` was introduced in [`OutputExecutor`](https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/components/output/OutputExecutor.ts) since I made my changes.

I had to just pass an empty metadata object to make it compile cause I don't have anything similar in context, not sure if it's correct. 

Pls check

**Comment by echarles** [comment]
> - was on the mountain trip without network coverage for long time(

Sounds super cool

Changes lgtm, still an build error on the CI

` src/components/output/OutputAdapter.ts(86,41): error TS2693: 'JSONObject' only refers to a type, but is being used as a value here.`

**Comment by sok82** [comment]
Sorry, had to work in blind mode - committed fix for this - `src/components/output/OutputAdapter.ts(86,41): error TS2693: 'JSONObject' only refers to a type, but is being used as a value here.`

**Review by echarles — APPROVED** [review]
LGTM Thx @sok82

**Pull request merged**
