### PR TITLE
feat: adding support to markdown cells (#247)

### PR DESCRIPTION
**Pull request by MarcosVn**
Written partially the solution for the #247. 

some issues still need to be discussed.

### CODE REVIEW

**Comment by MarcosVn** [comment]
Thank you very much for the feedback @echarles!

I have implemented the suggested changes (except for renaming `_codeCell` to `_cell`) and I already have a cell that can submit the markdown and get it rendered.

I am still working on some points that are not 100% okay, such as:

- When the markdown is rendered and clicking on the cell, it should go back to the input/editor;
- The cell size is not adjusting 100% automatically;
- Submitting the cell with shift + enter.

I will continue working on these points, but if you have any more direct suggestions, I would appreciate it!

One last issue that bothered me a bit is that I had to condition many places to the type of the cell (both in the `CellAdapter` and in `Cell`). Do you see a major problem with that?

**Comment by echarles** [comment]
Awesome!

> When the markdown is rendered and clicking on the cell, it should go back to the input/editor;

There is probably a listener to be added. The best would be to look at the core jupyterlab notebook and see how it is done there to reuse the existing machinery https://github.com/jupyterlab/jupyterlab/tree/main/packages/notebook-extension/src

> Submitting the cell with shift + enter (I am also evolving the CellCommands for this point).

Yes, CellCommands is where you have to add that shortcut.

> The cell height is not adjusting 100% automatically;

You mean when you resize the browser? of when you change the content of the cell?

> One last issue that bothered me a bit is that I had to condition many places to the type of the cell (both in the CellAdapter and in Cell). Do you see a major problem with that?

No ideal, but good for now.

**Comment by MarcosVn** [comment]
@echarles 

> There is probably a listener to be added. The best would be to look at the core jupyterlab notebook and see how it is done there to reuse the existing machinery https://github.com/jupyterlab/jupyterlab/tree/main/packages/notebook-extension/src

I am still investigating how this is done in JupyterLab, but there doesn't seem to be a registered command or anything that does this. The approach I am evaluating is having a DOM event to detect the double-click and from that, change the state of the cell (which I can already do).

> You mean when you resize the browser? of when you change the content of the cell?
It was about the cell content changing, but I believe it has already been resolved. Thank you!

**Comment by MarcosVn** [comment]
@echarles, I believe I have addressed all the points we discussed. I am doing another round of review and testing, and I will communicate here shortly so that a review can be done when possible.

**Comment by MarcosVn** [comment]
@echarles,
I submitted a version that is functional and I believe it is ready for review/testing.

Documenting a few points here:

>You mean when you resize the browser? of when you change the content of the cell?

When we change the content of the cell. For some reason this also only happens when the toolbar is active. In my use case, I initially don't want to use the default toolbar, so I "partially" created an interface to allow us to parameterize some UI aspects, such as whether the toolbar will be included in the `BoxPanel` or not. Please let me know if you disagree.

>The best would be to look at the core jupyterlab notebook and see how it is done there to reuse the existing machinery

I looked into the core packages and did not find any registered command that does this. It seems the implementation is indeed through event detection in the DOM and changing the state (rendered) from true to false. The implementation I did in (Cell.tsx) follows this approach.


In general, I also know that part of the code can be improved/enhanced, but I tried to do it in a "minimally viable" way without injecting too much complexity into the current code and components. Please point out anything you disagree with, and I will gladly make the adjustments.

**Comment by echarles** [comment]
Thank you so much @MarcosVn. I have checked the source and that looks good to me. We can for sure enhance further after.

I have run the CI and it was failing..

Failed tasks:
- @datalayer/jupyter-react:build
Error: Process completed with exit code 1.

I will still merge as it and come with a follow-up PR if needed.

**Review by echarles — APPROVED** [review]
LGTM Thx @MarcosVn

**Comment by MarcosVn** [comment]
Thank you!

**Comment by echarles** [comment]
@MarcosVn fyi https://github.com/datalayer/jupyter-ui/commit/8e688c943784f4bc5f65d405d15b2b8e0df0ce1a fixes the build.

**Pull request merged**
