### PR TITLE
Rework of monitoring output execution together with execution phase

### PR DESCRIPTION
**Pull request by sok82**
After hours of struggling with monitoring of output execution using `OutputAreaModel` changes I reworked previous functionality connected with monitoring to simple and convenient form of attaching one simple listener to output enabling user to monitor output changes.

Changes addressing rework of https://github.com/datalayer/jupyter-ui/issues/290.

Result is demonstrated in new example called `OutputWithMonitoring`

It works like this - attaching simple listener which gets new output area model and execution phase in one object

```ReactJS
...
  const handleExecutionPhaseChanged = (phaseOutput: IExecutionPhaseOutput) => {
    switch (phaseOutput.executionPhase) {
      case ExecutionPhase.running:
        const log = [new Date().toISOString() + ' EXECUTION PHASE - RUNNING'];
        setExecutionLog(log);
        break;
      case ExecutionPhase.completed:
        setExecutionLog(executionLog => [
          ...executionLog,
          new Date().toISOString() +
            ' EXECUTION PHASE - COMPLETED and output ' +
            JSON.stringify(phaseOutput.outputModel?.toJSON()),
        ]);
        break;
      case ExecutionPhase.completed_with_error:
        setExecutionLog(executionLog => [
          ...executionLog,
          new Date().toISOString() +
            ' EXECUTION PHASE - COMPLETED_WITH_ERROR and output ' +
            JSON.stringify(phaseOutput.outputModel?.toJSON()),
        ]);
        break;
    }
  };

...
<Output
        autoRun={false}
        code={code}
        id={id}
        kernel={defaultKernel}
        executeTrigger={execTrigger}
        outputs={output ? output : []}
        onExecutionPhaseChanged={handleExecutionPhaseChanged}
        suppressCodeExecutionErrors={true}
        showEditor
      />
```

Below you can find sceenshot with visual representation of monitored events - it works both when we have new output or when executor generates no output at all, or when execution completes with error

image

### CODE REVIEW

**Comment by sok82** [comment]
I checked few other examples linked with code execution (for example KernelExecution) - looks like they all work as before

**Comment by sok82** [comment]
Hey @echarles 

Do you have time today to check this?

I hope it's final (in short term) improvement that I need for my project to go further...

**Comment by echarles** [comment]
I am working atm on a branch with quite some changes. I will review and comment by tomrrow your changes, hopefully there will be no merge conflict, not sure.

**Comment by echarles** [comment]
@sok82 https://github.com/datalayer/jupyter-ui/pull/313 is just merged has has introduced conflict on your PR. Hopefully just change of the import. Could you rebase before I review it? Sorry again for the pain.

**Review by echarles — APPROVED** [review]
LGMT Thx @sok82

**Pull request merged**
