### PR TITLE
Enabling custom kernels for Cell.tsx (#332) (0.17.x)

### PR DESCRIPTION
**Pull request by MarcosVn**
Implements the solution proposed for #332

### CODE REVIEW

**Comment by MarcosVn** [comment]
Hey @echarles, I implemented the solution for #332. Could you review it when possible?

One possible issue is that we are currently using version 0.17.0 in our project. Would it be possible to have a parallel branch with version 0.17.1 including this enhancement? We intend to update the version on our side, but we wouldn’t be able to do it immediately.

**Comment by echarles** [comment]
Hi @MarcosVn Cell.tsx has conflict, would be great to solve that so I can review.

Happy to maintain a branch for you while you upgrade at some point.

**Comment by MarcosVn** [comment]
Hey @charles, I believe the conflict is happening because I'm pointing the pull request to the `main` branch and created it from `0.17.0`.

Would you prefer to create the `0.17.x` branch, or should I do it here?

Once we integrate this, I can open a second pull request to main as well, so we can have the updates in both places.

What do you think?

**Comment by echarles** [comment]
We don't maintain tags for now. If you provide me with the exact commit, I can create a 0.17.x branch.

Yes, a second pr on main will be great.

**Comment by MarcosVn** [comment]
@echarles the commit is: https://github.com/datalayer/jupyter-ui/commit/3ac5b261927f70a526f777b847ee84afc6ad4b3e

As soon as the `0.17.x` branch is created, I’ll point this PR to it and create the new branch for main, letting you know. Thanks in advance!

**Comment by echarles** [comment]
@MarcosVn https://github.com/datalayer/jupyter-ui/tree/0.17.x is available.

**Review by echarles — APPROVED** [review]
LGTM Thx @MarcosVn

**Comment by echarles** [comment]
Thank you @MarcosVn

**Comment by echarles** [comment]
@MarcosVn This is done in https://www.npmjs.com/package/@datalayer/jupyter-react/v/0.17.1

**Pull request merged**
