### PR TITLE
Fix for 301 - early registering of catch in promise for KernelExecutor

### PR DESCRIPTION
**Pull request by sok82**

### CODE REVIEW

**Comment by sok82** [comment]
Additional comments in https://github.com/datalayer/jupyter-ui/issues/301

**Comment by echarles** [comment]
@sok82 Can you add a specfic example OuptutWithErrorHandle on top of the existing Ouptut, so we are sure it works in both case?

PS: you have added a launch.json, this could be removed.

**Comment by sok82** [comment]
@echarles sure

> @sok82 Can you add a specfic example OuptutWithErrorHandle on top of the existing Ouptut, so we are sure it works in both case?
See update in new commit




> PS: you have added a launch.json, this could be removed.
Removed it

**Comment by echarles** [comment]
Awesome - I will be busy for the rest of my day and will look at this tomorrow morning. thx again.

**Review by echarles — APPROVED** [review]
LGTM Thx @sok82

**Pull request merged**
