### PR TITLE
feat: Create index.mdx with Amplify setup instructions under deployments docs

### PR DESCRIPTION
**Pull request by BrandonEscamilla**
Since I noticed that you upload the images to the S3 bucket, I have attached the images here for convenience. Please upload them to the bucket and use the respective image links in the documentation. Apologies for any inconvenience caused. Thank you in advance!

image-0: 
image-0-repository-setup

image-1: 
image-1-tab-settings

image-2:
image-2-app-settings

image-3
image-3-build-image-settings

### CODE REVIEW

**Comment by echarles** [comment]
Super! I have uploaded the images. Could you update your PR to link to them?

- https://datalayer-jupyter-examples.s3.us-east-1.amazonaws.com/deploy/amplify-get-started.png
- https://datalayer-jupyter-examples.s3.us-east-1.amazonaws.com/deploy/amplify-settings.png
- https://datalayer-jupyter-examples.s3.us-east-1.amazonaws.com/deploy/amplify-settings-build-image.png
- https://datalayer-jupyter-examples.s3.us-east-1.amazonaws.com/deploy/amplify-app-build-spec.png

**Comment by BrandonEscamilla** [comment]
Done! 😄

**Review by echarles — APPROVED** [review]
LGTM Thx @BrandonEscamilla

**Comment by echarles** [comment]
Live on https://jupyter-ui.datalayer.tech/docs/deployments/amplify/

**Pull request merged**
