### PR TITLE
feat: add support for multiple Cell state management (#255)

### PR DESCRIPTION
**Pull request by MarcosVn**
Implements the support for multiple Cell state management - #255. 

Some issues to be confirmed will be documented here.

### CODE REVIEW

**Comment by MarcosVn** [comment]
Hello, @echarles.

I submitted a minimal version to add the support we discussed. Could you review it when possible? I would be happy to make any necessary adjustments.

I also would like to document a few points here to align ourselves, please:

- **Adjustment of the CRA examples**
    - With the changes I made, we will need to update the CRA examples, but from what I saw, they use imports from the closed version of the library. How do you usually handle this? Do you release a version and correct them afterward?

- **Possibility to execute a cell (shift + enter) without triggering the execution of the others**
    - For the application I am building, it will be interesting to have the possibility to submit an individual cell with `shift + enter`, just as we have in the notebook itself. Today, the `Cell` behavior is to execute all cells together with this shortcut. Do you think it would be possible to include this behavior in this issue and implement it directly?

- **Usage of `isKernelAvailable`**
    - Since, initially, all cells share the same kernel (`defaultKernel`), I kept the `isKernelAvailable` attribute at the store level, not individual per cell. Do you see any problem with this?

- **Issue in `outputsCount`**
    - Personally, I won't need this in my application, but after doing some tests, I have the impression that the `outputsCount` is not beign set correctly. Even in version `0.10` or in older commits like `3197d240947f5e1ce80abe10801c3679e9cd5acc`, it is always `0` or `1`. Here is some evidence of this observation (and an error that only appears in the main library context for me):
    - image
    - image





Lastly, here is some evidence of the functionality:
-  image
- Synced notebook from individual cells (adding the output individually also)
  - image

**Comment by echarles** [comment]
Awesome @MarcosVn - Had a quick look to the changes and they look excellent.

> Adjustment of the CRA examples - Do you release a version and correct them afterward?

We typicall fix the examples present in this repo, release, and then update along the way the examples of the other repos.

> Possibility to execute a cell (shift + enter) without triggering the execution of the others

Shift+Enter in a cell should indeed trigger the execution of that specific cell, not all the others. I guess the command class needs to be made "multiple cell" also https://github.com/datalayer/jupyter-ui/blob/40257f125791afd0459a9beb4c07e8bb35ba7241/packages/react/src/components/cell/CellCommands.ts#L31-L37

> Usage of isKernelAvailable - Since, initially, all cells share the same kernel (defaultKernel), I kept the isKernelAvailable attribute at the store level, not individual per cell. Do you see any problem with this?

All good, That makes sense to me.

> Issue in outputsCount 

That may be another bug indeed and not related to your changes. Can you open a separated issue that describes that so we can track it?

**Comment by MarcosVn** [comment]
Hello, @echarles,

I addressed the issue with `Shift + Enter` here. It seemed to be associated with having a "global" keydown event that was detecting beyond the scope of the cell itself. In other words, pressing `Shift + Enter` was invoking the execute command for all cells (evidence below):

- image


The cleanest solution I found was to modify the listener to only add the `keydown` event for the current/scope cell, which isolates the event as expected.

I believe that with this, the PR can be reviewed, tested, and eventually approved. Could you please evaluate it for me? I am available for any adjustments that might be necessary.

Finally, if it gets approved, would it be possible to have a new version of the library with this update afterward?

Thank you very much in advance!

**Comment by echarles** [comment]
Awesome @MarcosVn 

I have just published @datalayer/jupyter-react@0.14.0 with your contribution 🎉

**Comment by MarcosVn** [comment]
Thank you, @echarles!

**Pull request merged**
